#!/bin/bash

#PBS -N OpenCL_Single
#PBS -o OUT
#PBS -q hpc-course
#PBS -l nodes=1:ppn=16:gpus=1,walltime=00:02:30
#PBS -n

#! Mail to user if job aborts
#PBS -m a


#! application name
application="d2q9-bgk.exe"

#! Run options for the application
options="../cfgs/input_1024x1024.params ../cfgs/obstacles_1024x1024_box.dat"

###############################################################
### You should not have to change anything below this line ####
###############################################################

#! change the working directory (default is home directory)

cd $PBS_O_WORKDIR

echo Running on host `hostname`
echo Time is `date`
echo Directory is `pwd`
echo PBS job ID is $PBS_JOBID
echo This jobs runs on the following GPUs:
echo `cat $PBS_GPUFILE | uniq`


#! Run the executable
$application $options
