#!/bin/bash

#PBS -N OpenCL_Size
#PBS -o OUT
#PBS -q hpc-course
#PBS -l nodes=1:ppn=16:gpus=1,walltime=00:30:00
#PBS -n

#! Mail to user if job aborts
#PBS -m a


#! application name
#application="d2q9-bgk.exe"
application="./run_sizes.sh"

#! Run options for the application
#options="cfgs/input_128x128.params cfgs/obstacles_128x128_box.dat"
options=""

###############################################################
### You should not have to change anything below this line ####
###############################################################

#! change the working directory (default is home directory)

cd $PBS_O_WORKDIR

echo Running on host `hostname`
echo Time is `date`
echo Directory is `pwd`
echo PBS job ID is $PBS_JOBID
echo This jobs runs on the following GPUs:
echo `cat $PBS_GPUFILE | uniq`


#! Run the executable
$application $options
