#!/bin/bash 
#!
#! Sample PBS file
#!
#! Name of job

#PBS -N MPI
#PBS -o OUT
#PBS -q hpc-course
#PBS -l nodes=4:ppn=16,walltime=00:03:00

#! Mail to user if job aborts
#PBS -m a

#! application name
application="./d2q9-bgk.exe"

#! Run options for the application
options="../cfgs/input_1024x1024.params ../cfgs/obstacles_1024x1024_box.dat"

###############################################################
### You should not have to change anything below this line ####
###############################################################

#! change the working directory (default is home directory)

cd $PBS_O_WORKDIR

echo Running on host `hostname`
echo Time is `date`
echo Directory is `pwd`
echo PBS job ID is $PBS_JOBID
echo This jobs runs on the following machines:
echo `cat $PBS_NODEFILE | uniq`

#! Create a machine file for MPI
cat $PBS_NODEFILE > machine.file.$PBS_JOBID

echo `wc $PBS_NODEFILE | awk '{ print $1 }'`

#! Run the executable. This command uses shared memory for local communication, infiniband otherwise
mpirun -env I_MPI_FABRICS shm:ofa -np 32 -machinefile machine.file.$PBS_JOBID $application $options

#! Use the following line to run the sim using TCP (ethernet).
#! mpirun -env I_MPI_FABRICS shm:tcp -np 64 -machinefile machine.file.$PBS_JOBID $application $options