#!/bin/sh
LEF="test${1}.le"
ASSF="test${1}.ass"

if [ -f "$LEF" ]
then
    if [ "$(hostname)" = "snowy.cs.bris.ac.uk" ]
    then
	if antlr3 camle "$LEF"
	then
	    ./assmule "$ASSF"
	else
	    antlr3 camle -irt "$LEF" | ./disptree | less
	fi
    else
	if ./antLEr3 camle "$LEF"
	then
	    less "$ASSF"
	else
	    ./antLEr3 camle -irt "$LEF" | less
	fi
    fi
else
    echo "Test $LEF does not exist!"
fi